
##################################################################
##
##    List of Source and Header Files.
##

library_source_files        =
LIBRARY_INSTANTIATIONS      =
LIBRARY_INLINE_FILES        =

dist_noinst_data_files      =  CMakeLists.txt
dist_noinst_header_files    =

inclib_header_files         =
inclib_nodist_header_files  =

library_install_srcfiles    =
library_compile_srcfiles    =


##################################################################
##
##    List of Libraries.
##

static_libraries_list   =
shared_libraries_list   =


##################################################################
##
##    Compile and Link Options.
##

AM_CPPFLAGS             =  -I${inctop_source_dir}
AM_CFLAGS               =
AM_CXXFLAGS             =
