
##################################################################
##
##    List of Source and Header Files.
##

library_source_files        =
LIBRARY_INSTANTIATIONS      =
LIBRARY_INLINE_FILES        =

dist_noinst_data_files      =  CMakeLists.txt
dist_noinst_header_files    =

INCLIB_HEADER_FILES         =

INCLIB_NODIST_HEADER_FILES  =

LIBRARY_INSTALL_SRCFILES    =

LIBRARY_COMPILE_SRCFILES    =


##################################################################
##
##    List of Libraries.
##

STATIC_LIBRARIES_LIST   =
SHARED_LIBRARIES_LIST   =


##################################################################
##
##    Compile and Link Options.
##

AM_CPPFLAGS             =  -I${inctop_source_dir}
AM_CFLAGS               =
AM_CXXFLAGS             =
